import type { ReactNode } from 'react';
import '../styles/tailwind.css';
import { Roboto_Flex } from 'next/font/google';
import { Nav } from '@/components/inc/nav/Nav';

const robotoFlex = Roboto_Flex({
	subsets: ['latin'],
	style: 'normal',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = {
	children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="pl" className={robotoFlex.className}>
			<body className="bg-theme-base">
				<Nav />

				<main>{children}</main>
			</body>
		</html>
	);
}
